name: Deploy Workflow

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print API Key
      run: echo "API_KEY=$API_KEY"
      env:
        API_KEY: ${{ secrets.API_KEY }}
